// Code generated by vulkangen. DO NOT EDIT.

package vulkan

var VkCreateInstance func(*InstanceCreateInfo, *AllocationCallbacks, *Instance) Result
var VkDestroyInstance func(Instance, *AllocationCallbacks)
var VkEnumeratePhysicalDevices func(Instance, *uint32, *PhysicalDevice) Result
var VkGetDeviceProcAddr func(Device, *byte) PFN_vkVoidFunction
var VkGetInstanceProcAddr func(Instance, *byte) PFN_vkVoidFunction
var VkGetPhysicalDeviceProperties func(PhysicalDevice, *PhysicalDeviceProperties)
var VkGetPhysicalDeviceQueueFamilyProperties func(PhysicalDevice, *uint32, *QueueFamilyProperties)
var VkCreateDevice func(PhysicalDevice, *DeviceCreateInfo, *AllocationCallbacks, *Device) Result
var VkDestroyDevice func(Device, *AllocationCallbacks)
var VkEnumerateInstanceVersion func(*uint32) Result
var VkEnumerateInstanceLayerProperties func(*uint32, *LayerProperties) Result
var VkEnumerateInstanceExtensionProperties func(*byte, *uint32, *ExtensionProperties) Result
var VkEnumerateDeviceExtensionProperties func(PhysicalDevice, *byte, *uint32, *ExtensionProperties) Result
var VkGetDeviceQueue func(Device, uint32, uint32, *Queue)
var VkQueueSubmit func(Queue, uint32, *SubmitInfo, Fence) Result
var VkQueueWaitIdle func(Queue) Result
var VkDeviceWaitIdle func(Device) Result
var VkAllocateMemory func(Device, *MemoryAllocateInfo, *AllocationCallbacks, *DeviceMemory) Result
var VkFreeMemory func(Device, DeviceMemory, *AllocationCallbacks)
var VkGetImageMemoryRequirements func(Device, Image, *MemoryRequirements)
var VkBindImageMemory func(Device, Image, DeviceMemory, DeviceSize) Result
var VkCreateFence func(Device, *FenceCreateInfo, *AllocationCallbacks, *Fence) Result
var VkDestroyFence func(Device, Fence, *AllocationCallbacks)
var VkResetFences func(Device, uint32, *Fence) Result
var VkWaitForFences func(Device, uint32, *Fence, Bool32, uint64) Result
var VkCreateSemaphore func(Device, *SemaphoreCreateInfo, *AllocationCallbacks, *Semaphore) Result
var VkDestroySemaphore func(Device, Semaphore, *AllocationCallbacks)
var VkCreateImage func(Device, *ImageCreateInfo, *AllocationCallbacks, *Image) Result
var VkDestroyImage func(Device, Image, *AllocationCallbacks)
var VkCreateImageView func(Device, *ImageViewCreateInfo, *AllocationCallbacks, *ImageView) Result
var VkDestroyImageView func(Device, ImageView, *AllocationCallbacks)
var VkCreateShaderModule func(Device, *ShaderModuleCreateInfo, *AllocationCallbacks, *ShaderModule) Result
var VkDestroyShaderModule func(Device, ShaderModule, *AllocationCallbacks)
var VkCreatePipelineLayout func(Device, *PipelineLayoutCreateInfo, *AllocationCallbacks, *PipelineLayout) Result
var VkDestroyPipelineLayout func(Device, PipelineLayout, *AllocationCallbacks)
var VkCreateSampler func(Device, *SamplerCreateInfo, *AllocationCallbacks, *Sampler) Result
var VkDestroySampler func(Device, Sampler, *AllocationCallbacks)
var VkCreateDescriptorSetLayout func(Device, *DescriptorSetLayoutCreateInfo, *AllocationCallbacks, *DescriptorSetLayout) Result
var VkDestroyDescriptorSetLayout func(Device, DescriptorSetLayout, *AllocationCallbacks)
var VkCreateDescriptorPool func(Device, *DescriptorPoolCreateInfo, *AllocationCallbacks, *DescriptorPool) Result
var VkDestroyDescriptorPool func(Device, DescriptorPool, *AllocationCallbacks)
var VkAllocateDescriptorSets func(Device, *DescriptorSetAllocateInfo, *DescriptorSet) Result
var VkUpdateDescriptorSets func(Device, uint32, *WriteDescriptorSet, uint32, *CopyDescriptorSet)
var VkCreateCommandPool func(Device, *CommandPoolCreateInfo, *AllocationCallbacks, *CommandPool) Result
var VkDestroyCommandPool func(Device, CommandPool, *AllocationCallbacks)
var VkAllocateCommandBuffers func(Device, *CommandBufferAllocateInfo, *CommandBuffer) Result
var VkFreeCommandBuffers func(Device, CommandPool, uint32, *CommandBuffer)
var VkBeginCommandBuffer func(CommandBuffer, *CommandBufferBeginInfo) Result
var VkEndCommandBuffer func(CommandBuffer) Result
var VkResetCommandBuffer func(CommandBuffer, CommandBufferResetFlags) Result
var VkGetPhysicalDeviceFeatures2 func(PhysicalDevice, *PhysicalDeviceFeatures2)
var VkGetPhysicalDeviceFeatures2KHR func(PhysicalDevice, *PhysicalDeviceFeatures2)
var VkGetPhysicalDeviceProperties2 func(PhysicalDevice, *PhysicalDeviceProperties2)
var VkGetPhysicalDeviceProperties2KHR func(PhysicalDevice, *PhysicalDeviceProperties2)
var VkGetPhysicalDeviceFormatProperties2KHR func(PhysicalDevice, Format, *FormatProperties2)
var VkGetPhysicalDeviceImageFormatProperties2KHR func(PhysicalDevice, *PhysicalDeviceImageFormatInfo2, *ImageFormatProperties2) Result
var VkGetPhysicalDeviceQueueFamilyProperties2 func(PhysicalDevice, *uint32, *QueueFamilyProperties2)
var VkGetPhysicalDeviceQueueFamilyProperties2KHR func(PhysicalDevice, *uint32, *QueueFamilyProperties2)
var VkGetPhysicalDeviceMemoryProperties2KHR func(PhysicalDevice, *PhysicalDeviceMemoryProperties2)
var VkGetPhysicalDeviceSparseImageFormatProperties2KHR func(PhysicalDevice, *PhysicalDeviceSparseImageFormatInfo2, *uint32, *SparseImageFormatProperties2)
var VkTrimCommandPoolKHR func(Device, CommandPool, CommandPoolTrimFlags)
var VkGetPhysicalDeviceExternalBufferPropertiesKHR func(PhysicalDevice, *PhysicalDeviceExternalBufferInfo, *ExternalBufferProperties)
var VkGetMemoryFdKHR func(Device, *MemoryGetFdInfoKHR, *int32) Result
var VkGetMemoryFdPropertiesKHR func(Device, ExternalMemoryHandleTypeFlagBits, int32, *MemoryFdPropertiesKHR) Result
var VkGetPhysicalDeviceExternalSemaphorePropertiesKHR func(PhysicalDevice, *PhysicalDeviceExternalSemaphoreInfo, *ExternalSemaphoreProperties)
var VkGetSemaphoreFdKHR func(Device, *SemaphoreGetFdInfoKHR, *int32) Result
var VkImportSemaphoreFdKHR func(Device, *ImportSemaphoreFdInfoKHR) Result
var VkBindBufferMemory2KHR func(Device, uint32, *BindBufferMemoryInfo) Result
var VkBindImageMemory2 func(Device, uint32, *BindImageMemoryInfo) Result
var VkBindImageMemory2KHR func(Device, uint32, *BindImageMemoryInfo) Result
var VkGetBufferMemoryRequirements2KHR func(Device, *BufferMemoryRequirementsInfo2, *MemoryRequirements2)
var VkGetImageMemoryRequirements2 func(Device, *ImageMemoryRequirementsInfo2, *MemoryRequirements2)
var VkGetImageMemoryRequirements2KHR func(Device, *ImageMemoryRequirementsInfo2, *MemoryRequirements2)
var VkGetImageSparseMemoryRequirements2KHR func(Device, *ImageSparseMemoryRequirementsInfo2, *uint32, *SparseImageMemoryRequirements2)
var VkCreateSamplerYcbcrConversionKHR func(Device, *SamplerYcbcrConversionCreateInfo, *AllocationCallbacks, *SamplerYcbcrConversion) Result
var VkDestroySamplerYcbcrConversionKHR func(Device, SamplerYcbcrConversion, *AllocationCallbacks)
var VkGetImageDrmFormatModifierPropertiesEXT func(Device, Image, *ImageDrmFormatModifierPropertiesEXT) Result
var VkCmdSetEvent2KHR func(CommandBuffer, Event, *DependencyInfo)
var VkCmdResetEvent2KHR func(CommandBuffer, Event, PipelineStageFlags2)
var VkCmdWaitEvents2KHR func(CommandBuffer, uint32, *Event, *DependencyInfo)
var VkCmdPipelineBarrier2KHR func(CommandBuffer, *DependencyInfo)
var VkQueueSubmit2KHR func(Queue, uint32, *SubmitInfo2, Fence) Result
var VkCmdWriteTimestamp2KHR func(CommandBuffer, PipelineStageFlags2, QueryPool, uint32)

func globalCommandPointers() map[string]any {
	return map[string]any{
		"vkCreateInstance":                       &VkCreateInstance,
		"vkGetInstanceProcAddr":                  &VkGetInstanceProcAddr,
		"vkEnumerateInstanceVersion":             &VkEnumerateInstanceVersion,
		"vkEnumerateInstanceLayerProperties":     &VkEnumerateInstanceLayerProperties,
		"vkEnumerateInstanceExtensionProperties": &VkEnumerateInstanceExtensionProperties,
	}
}

func instanceCommandPointers() map[string]any {
	return map[string]any{
		"vkDestroyInstance":                                  &VkDestroyInstance,
		"vkEnumeratePhysicalDevices":                         &VkEnumeratePhysicalDevices,
		"vkGetDeviceProcAddr":                                &VkGetDeviceProcAddr,
		"vkGetPhysicalDeviceProperties":                      &VkGetPhysicalDeviceProperties,
		"vkGetPhysicalDeviceQueueFamilyProperties":           &VkGetPhysicalDeviceQueueFamilyProperties,
		"vkCreateDevice":                                     &VkCreateDevice,
		"vkEnumerateDeviceExtensionProperties":               &VkEnumerateDeviceExtensionProperties,
		"vkGetPhysicalDeviceFeatures2":                       &VkGetPhysicalDeviceFeatures2,
		"vkGetPhysicalDeviceFeatures2KHR":                    &VkGetPhysicalDeviceFeatures2KHR,
		"vkGetPhysicalDeviceProperties2":                     &VkGetPhysicalDeviceProperties2,
		"vkGetPhysicalDeviceProperties2KHR":                  &VkGetPhysicalDeviceProperties2KHR,
		"vkGetPhysicalDeviceFormatProperties2KHR":            &VkGetPhysicalDeviceFormatProperties2KHR,
		"vkGetPhysicalDeviceImageFormatProperties2KHR":       &VkGetPhysicalDeviceImageFormatProperties2KHR,
		"vkGetPhysicalDeviceQueueFamilyProperties2":          &VkGetPhysicalDeviceQueueFamilyProperties2,
		"vkGetPhysicalDeviceQueueFamilyProperties2KHR":       &VkGetPhysicalDeviceQueueFamilyProperties2KHR,
		"vkGetPhysicalDeviceMemoryProperties2KHR":            &VkGetPhysicalDeviceMemoryProperties2KHR,
		"vkGetPhysicalDeviceSparseImageFormatProperties2KHR": &VkGetPhysicalDeviceSparseImageFormatProperties2KHR,
		"vkGetPhysicalDeviceExternalBufferPropertiesKHR":     &VkGetPhysicalDeviceExternalBufferPropertiesKHR,
		"vkGetPhysicalDeviceExternalSemaphorePropertiesKHR":  &VkGetPhysicalDeviceExternalSemaphorePropertiesKHR,
	}
}

func deviceCommandPointers() map[string]any {
	return map[string]any{
		"vkDestroyDevice":                          &VkDestroyDevice,
		"vkGetDeviceQueue":                         &VkGetDeviceQueue,
		"vkQueueSubmit":                            &VkQueueSubmit,
		"vkQueueWaitIdle":                          &VkQueueWaitIdle,
		"vkDeviceWaitIdle":                         &VkDeviceWaitIdle,
		"vkAllocateMemory":                         &VkAllocateMemory,
		"vkFreeMemory":                             &VkFreeMemory,
		"vkGetImageMemoryRequirements":             &VkGetImageMemoryRequirements,
		"vkBindImageMemory":                        &VkBindImageMemory,
		"vkCreateFence":                            &VkCreateFence,
		"vkDestroyFence":                           &VkDestroyFence,
		"vkResetFences":                            &VkResetFences,
		"vkWaitForFences":                          &VkWaitForFences,
		"vkCreateSemaphore":                        &VkCreateSemaphore,
		"vkDestroySemaphore":                       &VkDestroySemaphore,
		"vkCreateImage":                            &VkCreateImage,
		"vkDestroyImage":                           &VkDestroyImage,
		"vkCreateImageView":                        &VkCreateImageView,
		"vkDestroyImageView":                       &VkDestroyImageView,
		"vkCreateShaderModule":                     &VkCreateShaderModule,
		"vkDestroyShaderModule":                    &VkDestroyShaderModule,
		"vkCreatePipelineLayout":                   &VkCreatePipelineLayout,
		"vkDestroyPipelineLayout":                  &VkDestroyPipelineLayout,
		"vkCreateSampler":                          &VkCreateSampler,
		"vkDestroySampler":                         &VkDestroySampler,
		"vkCreateDescriptorSetLayout":              &VkCreateDescriptorSetLayout,
		"vkDestroyDescriptorSetLayout":             &VkDestroyDescriptorSetLayout,
		"vkCreateDescriptorPool":                   &VkCreateDescriptorPool,
		"vkDestroyDescriptorPool":                  &VkDestroyDescriptorPool,
		"vkAllocateDescriptorSets":                 &VkAllocateDescriptorSets,
		"vkUpdateDescriptorSets":                   &VkUpdateDescriptorSets,
		"vkCreateCommandPool":                      &VkCreateCommandPool,
		"vkDestroyCommandPool":                     &VkDestroyCommandPool,
		"vkAllocateCommandBuffers":                 &VkAllocateCommandBuffers,
		"vkFreeCommandBuffers":                     &VkFreeCommandBuffers,
		"vkBeginCommandBuffer":                     &VkBeginCommandBuffer,
		"vkEndCommandBuffer":                       &VkEndCommandBuffer,
		"vkResetCommandBuffer":                     &VkResetCommandBuffer,
		"vkTrimCommandPoolKHR":                     &VkTrimCommandPoolKHR,
		"vkGetMemoryFdKHR":                         &VkGetMemoryFdKHR,
		"vkGetMemoryFdPropertiesKHR":               &VkGetMemoryFdPropertiesKHR,
		"vkGetSemaphoreFdKHR":                      &VkGetSemaphoreFdKHR,
		"vkImportSemaphoreFdKHR":                   &VkImportSemaphoreFdKHR,
		"vkBindBufferMemory2KHR":                   &VkBindBufferMemory2KHR,
		"vkBindImageMemory2":                       &VkBindImageMemory2,
		"vkBindImageMemory2KHR":                    &VkBindImageMemory2KHR,
		"vkGetBufferMemoryRequirements2KHR":        &VkGetBufferMemoryRequirements2KHR,
		"vkGetImageMemoryRequirements2":            &VkGetImageMemoryRequirements2,
		"vkGetImageMemoryRequirements2KHR":         &VkGetImageMemoryRequirements2KHR,
		"vkGetImageSparseMemoryRequirements2KHR":   &VkGetImageSparseMemoryRequirements2KHR,
		"vkCreateSamplerYcbcrConversionKHR":        &VkCreateSamplerYcbcrConversionKHR,
		"vkDestroySamplerYcbcrConversionKHR":       &VkDestroySamplerYcbcrConversionKHR,
		"vkGetImageDrmFormatModifierPropertiesEXT": &VkGetImageDrmFormatModifierPropertiesEXT,
		"vkCmdSetEvent2KHR":                        &VkCmdSetEvent2KHR,
		"vkCmdResetEvent2KHR":                      &VkCmdResetEvent2KHR,
		"vkCmdWaitEvents2KHR":                      &VkCmdWaitEvents2KHR,
		"vkCmdPipelineBarrier2KHR":                 &VkCmdPipelineBarrier2KHR,
		"vkQueueSubmit2KHR":                        &VkQueueSubmit2KHR,
		"vkCmdWriteTimestamp2KHR":                  &VkCmdWriteTimestamp2KHR,
	}
}
