// Code generated by vulkangen. DO NOT EDIT.

package vulkan

import "unsafe"

type GlobalDispatch struct {
	CreateInstance                       func(*InstanceCreateInfo, *AllocationCallbacks, *Instance) Result
	GetInstanceProcAddr                  func(Instance, *byte) PFN_vkVoidFunction
	EnumerateInstanceVersion             func(*uint32) Result
	EnumerateInstanceLayerProperties     func(*uint32, *LayerProperties) Result
	EnumerateInstanceExtensionProperties func(*byte, *uint32, *ExtensionProperties) Result
}

type InstanceDispatch struct {
	Instance                                         Instance
	DestroyInstance                                  func(Instance, *AllocationCallbacks)
	EnumeratePhysicalDevices                         func(Instance, *uint32, *PhysicalDevice) Result
	GetDeviceProcAddr                                func(Device, *byte) PFN_vkVoidFunction
	GetPhysicalDeviceProperties                      func(PhysicalDevice, *PhysicalDeviceProperties)
	GetPhysicalDeviceQueueFamilyProperties           func(PhysicalDevice, *uint32, *QueueFamilyProperties)
	CreateDevice                                     func(PhysicalDevice, *DeviceCreateInfo, *AllocationCallbacks, *Device) Result
	EnumerateDeviceExtensionProperties               func(PhysicalDevice, *byte, *uint32, *ExtensionProperties) Result
	GetPhysicalDeviceFeatures2                       func(PhysicalDevice, *PhysicalDeviceFeatures2)
	GetPhysicalDeviceFeatures2KHR                    func(PhysicalDevice, *PhysicalDeviceFeatures2)
	GetPhysicalDeviceProperties2                     func(PhysicalDevice, *PhysicalDeviceProperties2)
	GetPhysicalDeviceProperties2KHR                  func(PhysicalDevice, *PhysicalDeviceProperties2)
	GetPhysicalDeviceFormatProperties2KHR            func(PhysicalDevice, Format, *FormatProperties2)
	GetPhysicalDeviceImageFormatProperties2KHR       func(PhysicalDevice, *PhysicalDeviceImageFormatInfo2, *ImageFormatProperties2) Result
	GetPhysicalDeviceQueueFamilyProperties2          func(PhysicalDevice, *uint32, *QueueFamilyProperties2)
	GetPhysicalDeviceQueueFamilyProperties2KHR       func(PhysicalDevice, *uint32, *QueueFamilyProperties2)
	GetPhysicalDeviceMemoryProperties2KHR            func(PhysicalDevice, *PhysicalDeviceMemoryProperties2)
	GetPhysicalDeviceSparseImageFormatProperties2KHR func(PhysicalDevice, *PhysicalDeviceSparseImageFormatInfo2, *uint32, *SparseImageFormatProperties2)
	GetPhysicalDeviceExternalSemaphorePropertiesKHR  func(PhysicalDevice, *PhysicalDeviceExternalSemaphoreInfo, *ExternalSemaphoreProperties)
}

type DeviceDispatch struct {
	Device                                 Device
	DestroyDevice                          func(Device, *AllocationCallbacks)
	GetDeviceQueue                         func(Device, uint32, uint32, *Queue)
	QueueSubmit                            func(Queue, uint32, *SubmitInfo, Fence) Result
	QueueWaitIdle                          func(Queue) Result
	DeviceWaitIdle                         func(Device) Result
	AllocateMemory                         func(Device, *MemoryAllocateInfo, *AllocationCallbacks, *DeviceMemory) Result
	FreeMemory                             func(Device, DeviceMemory, *AllocationCallbacks)
	MapMemory                              func(Device, DeviceMemory, DeviceSize, DeviceSize, MemoryMapFlags, **unsafe.Pointer) Result
	UnmapMemory                            func(Device, DeviceMemory)
	FlushMappedMemoryRanges                func(Device, uint32, *MappedMemoryRange) Result
	InvalidateMappedMemoryRanges           func(Device, uint32, *MappedMemoryRange) Result
	GetBufferMemoryRequirements            func(Device, Buffer, *MemoryRequirements)
	BindBufferMemory                       func(Device, Buffer, DeviceMemory, DeviceSize) Result
	GetImageMemoryRequirements             func(Device, Image, *MemoryRequirements)
	BindImageMemory                        func(Device, Image, DeviceMemory, DeviceSize) Result
	CreateFence                            func(Device, *FenceCreateInfo, *AllocationCallbacks, *Fence) Result
	DestroyFence                           func(Device, Fence, *AllocationCallbacks)
	ResetFences                            func(Device, uint32, *Fence) Result
	WaitForFences                          func(Device, uint32, *Fence, Bool32, uint64) Result
	CreateSemaphore                        func(Device, *SemaphoreCreateInfo, *AllocationCallbacks, *Semaphore) Result
	DestroySemaphore                       func(Device, Semaphore, *AllocationCallbacks)
	CreateBuffer                           func(Device, *BufferCreateInfo, *AllocationCallbacks, *Buffer) Result
	DestroyBuffer                          func(Device, Buffer, *AllocationCallbacks)
	CreateImage                            func(Device, *ImageCreateInfo, *AllocationCallbacks, *Image) Result
	DestroyImage                           func(Device, Image, *AllocationCallbacks)
	CreateImageView                        func(Device, *ImageViewCreateInfo, *AllocationCallbacks, *ImageView) Result
	DestroyImageView                       func(Device, ImageView, *AllocationCallbacks)
	CreateShaderModule                     func(Device, *ShaderModuleCreateInfo, *AllocationCallbacks, *ShaderModule) Result
	DestroyShaderModule                    func(Device, ShaderModule, *AllocationCallbacks)
	CreateGraphicsPipelines                func(Device, PipelineCache, uint32, *GraphicsPipelineCreateInfo, *AllocationCallbacks, *Pipeline) Result
	DestroyPipeline                        func(Device, Pipeline, *AllocationCallbacks)
	CreatePipelineLayout                   func(Device, *PipelineLayoutCreateInfo, *AllocationCallbacks, *PipelineLayout) Result
	DestroyPipelineLayout                  func(Device, PipelineLayout, *AllocationCallbacks)
	CreateSampler                          func(Device, *SamplerCreateInfo, *AllocationCallbacks, *Sampler) Result
	DestroySampler                         func(Device, Sampler, *AllocationCallbacks)
	CreateDescriptorSetLayout              func(Device, *DescriptorSetLayoutCreateInfo, *AllocationCallbacks, *DescriptorSetLayout) Result
	DestroyDescriptorSetLayout             func(Device, DescriptorSetLayout, *AllocationCallbacks)
	CreateDescriptorPool                   func(Device, *DescriptorPoolCreateInfo, *AllocationCallbacks, *DescriptorPool) Result
	DestroyDescriptorPool                  func(Device, DescriptorPool, *AllocationCallbacks)
	AllocateDescriptorSets                 func(Device, *DescriptorSetAllocateInfo, *DescriptorSet) Result
	UpdateDescriptorSets                   func(Device, uint32, *WriteDescriptorSet, uint32, *CopyDescriptorSet)
	CreateCommandPool                      func(Device, *CommandPoolCreateInfo, *AllocationCallbacks, *CommandPool) Result
	DestroyCommandPool                     func(Device, CommandPool, *AllocationCallbacks)
	AllocateCommandBuffers                 func(Device, *CommandBufferAllocateInfo, *CommandBuffer) Result
	FreeCommandBuffers                     func(Device, CommandPool, uint32, *CommandBuffer)
	BeginCommandBuffer                     func(CommandBuffer, *CommandBufferBeginInfo) Result
	EndCommandBuffer                       func(CommandBuffer) Result
	ResetCommandBuffer                     func(CommandBuffer, CommandBufferResetFlags) Result
	CmdBindPipeline                        func(CommandBuffer, PipelineBindPoint, Pipeline)
	CmdBindDescriptorSets                  func(CommandBuffer, PipelineBindPoint, PipelineLayout, uint32, uint32, *DescriptorSet, uint32, *uint32)
	CmdBindIndexBuffer                     func(CommandBuffer, Buffer, DeviceSize, IndexType)
	CmdBindVertexBuffers                   func(CommandBuffer, uint32, uint32, *Buffer, *DeviceSize)
	CmdDraw                                func(CommandBuffer, uint32, uint32, uint32, uint32)
	CmdDrawIndexed                         func(CommandBuffer, uint32, uint32, uint32, int32, uint32)
	CmdCopyBufferToImage                   func(CommandBuffer, Buffer, Image, ImageLayout, uint32, *BufferImageCopy)
	GetMemoryFdKHR                         func(Device, *MemoryGetFdInfoKHR, *int32) Result
	GetMemoryFdPropertiesKHR               func(Device, ExternalMemoryHandleTypeFlagBits, int32, *MemoryFdPropertiesKHR) Result
	GetSemaphoreFdKHR                      func(Device, *SemaphoreGetFdInfoKHR, *int32) Result
	ImportSemaphoreFdKHR                   func(Device, *ImportSemaphoreFdInfoKHR) Result
	BindBufferMemory2KHR                   func(Device, uint32, *BindBufferMemoryInfo) Result
	BindImageMemory2                       func(Device, uint32, *BindImageMemoryInfo) Result
	BindImageMemory2KHR                    func(Device, uint32, *BindImageMemoryInfo) Result
	GetBufferMemoryRequirements2KHR        func(Device, *BufferMemoryRequirementsInfo2, *MemoryRequirements2)
	GetImageMemoryRequirements2            func(Device, *ImageMemoryRequirementsInfo2, *MemoryRequirements2)
	GetImageMemoryRequirements2KHR         func(Device, *ImageMemoryRequirementsInfo2, *MemoryRequirements2)
	GetImageSparseMemoryRequirements2KHR   func(Device, *ImageSparseMemoryRequirementsInfo2, *uint32, *SparseImageMemoryRequirements2)
	GetImageDrmFormatModifierPropertiesEXT func(Device, Image, *ImageDrmFormatModifierPropertiesEXT) Result
	CmdSetEvent2KHR                        func(CommandBuffer, Event, *DependencyInfo)
	CmdResetEvent2KHR                      func(CommandBuffer, Event, PipelineStageFlags2)
	CmdWaitEvents2KHR                      func(CommandBuffer, uint32, *Event, *DependencyInfo)
	CmdPipelineBarrier2KHR                 func(CommandBuffer, *DependencyInfo)
	QueueSubmit2KHR                        func(Queue, uint32, *SubmitInfo2, Fence) Result
	CmdWriteTimestamp2KHR                  func(CommandBuffer, PipelineStageFlags2, QueryPool, uint32)
	CmdBeginRendering                      func(CommandBuffer, *RenderingInfo)
	CmdBeginRenderingKHR                   func(CommandBuffer, *RenderingInfo)
	CmdEndRendering                        func(CommandBuffer)
	CmdEndRenderingKHR                     func(CommandBuffer)
}
