// Code generated by vulkangen. DO NOT EDIT.

package vulkan

import "unsafe"

type Bool32 uint32

type Flags uint32

type Flags64 uint64

type DeviceSize uint64

type SamplerCreateFlags uint32

type PipelineLayoutCreateFlags uint32

type DescriptorSetLayoutCreateFlags uint32

type InstanceCreateFlags uint32

type DeviceCreateFlags uint32

type DeviceQueueCreateFlags uint32

type QueueFlags uint32

type MemoryPropertyFlags uint32

type MemoryHeapFlags uint32

type BufferUsageFlags uint32

type BufferCreateFlags uint32

type ShaderStageFlags uint32

type ImageUsageFlags uint32

type ImageCreateFlags uint32

type ImageViewCreateFlags uint32

type FenceCreateFlags uint32

type SemaphoreCreateFlags uint32

type FormatFeatureFlags uint32

type QueryControlFlags uint32

type ShaderModuleCreateFlags uint32

type CommandPoolCreateFlags uint32

type CommandBufferResetFlags uint32

type CommandBufferUsageFlags uint32

type QueryPipelineStatisticFlags uint32

type ImageAspectFlags uint32

type SparseImageFormatFlags uint32

type PipelineStageFlags uint32

type SampleCountFlags uint32

type DescriptorPoolCreateFlags uint32

type DependencyFlags uint32

type AccessFlags2 uint64

type AccessFlags2KHR = AccessFlags2

type PipelineStageFlags2 uint64

type PipelineStageFlags2KHR = PipelineStageFlags2

type CommandPoolTrimFlags uint32

type CommandPoolTrimFlagsKHR = CommandPoolTrimFlags

type ExternalMemoryHandleTypeFlags uint32

type ExternalMemoryHandleTypeFlagsKHR = ExternalMemoryHandleTypeFlags

type ExternalMemoryFeatureFlags uint32

type ExternalMemoryFeatureFlagsKHR = ExternalMemoryFeatureFlags

type ExternalSemaphoreHandleTypeFlags uint32

type ExternalSemaphoreHandleTypeFlagsKHR = ExternalSemaphoreHandleTypeFlags

type ExternalSemaphoreFeatureFlags uint32

type ExternalSemaphoreFeatureFlagsKHR = ExternalSemaphoreFeatureFlags

type SemaphoreImportFlags uint32

type SemaphoreImportFlagsKHR = SemaphoreImportFlags

type SubmitFlags uint32

type SubmitFlagsKHR = SubmitFlags

type Instance uintptr

type PhysicalDevice uintptr

type Device uintptr

type Queue uintptr

type CommandBuffer uintptr

type DeviceMemory uint64

type CommandPool uint64

type Buffer uint64

type BufferView uint64

type Image uint64

type ImageView uint64

type ShaderModule uint64

type PipelineLayout uint64

type Sampler uint64

type DescriptorSet uint64

type DescriptorSetLayout uint64

type DescriptorPool uint64

type Fence uint64

type Semaphore uint64

type Event uint64

type QueryPool uint64

type Framebuffer uint64

type RenderPass uint64

type SamplerYcbcrConversion uint64

type SamplerYcbcrConversionKHR = SamplerYcbcrConversion

type BorderColor int32

type SamplerCreateFlagBits int32

type DescriptorSetLayoutCreateFlagBits int32

type InstanceCreateFlagBits int32

type DeviceQueueCreateFlagBits int32

type BufferCreateFlagBits int32

type BufferUsageFlagBits int32

type ComponentSwizzle int32

type CommandPoolCreateFlagBits int32

type CommandBufferResetFlagBits int32

type CommandBufferLevel int32

type CommandBufferUsageFlagBits int32

type CompareOp int32

type DescriptorType int32

type FenceCreateFlagBits int32

type Format int32

type FormatFeatureFlagBits int32

type ImageAspectFlagBits int32

type ImageCreateFlagBits int32

type ImageLayout int32

type ImageTiling int32

type ImageType int32

type ImageUsageFlagBits int32

type ImageViewCreateFlagBits int32

type ImageViewType int32

type SharingMode int32

type MemoryHeapFlagBits int32

type MemoryPropertyFlagBits int32

type PhysicalDeviceType int32

type QueryControlFlagBits int32

type QueryPipelineStatisticFlagBits int32

type QueueFlagBits int32

type Result int32

type ShaderStageFlagBits int32

type StructureType int32

type SamplerAddressMode int32

type Filter int32

type SamplerMipmapMode int32

type PipelineStageFlagBits int32

type SparseImageFormatFlagBits int32

type SampleCountFlagBits int32

type DescriptorPoolCreateFlagBits int32

type DependencyFlagBits int32

type PipelineLayoutCreateFlagBits int32

type AccessFlagBits2 int32

type AccessFlagBits2KHR = AccessFlagBits2

type PipelineStageFlagBits2 int32

type PipelineStageFlagBits2KHR = PipelineStageFlagBits2

type ExternalMemoryHandleTypeFlagBits int32

type ExternalMemoryHandleTypeFlagBitsKHR = ExternalMemoryHandleTypeFlagBits

type ExternalMemoryFeatureFlagBits int32

type ExternalMemoryFeatureFlagBitsKHR = ExternalMemoryFeatureFlagBits

type ExternalSemaphoreHandleTypeFlagBits int32

type ExternalSemaphoreHandleTypeFlagBitsKHR = ExternalSemaphoreHandleTypeFlagBits

type ExternalSemaphoreFeatureFlagBits int32

type ExternalSemaphoreFeatureFlagBitsKHR = ExternalSemaphoreFeatureFlagBits

type SemaphoreImportFlagBits int32

type SemaphoreImportFlagBitsKHR = SemaphoreImportFlagBits

type SamplerYcbcrModelConversion int32

type SamplerYcbcrModelConversionKHR = SamplerYcbcrModelConversion

type SamplerYcbcrRange int32

type SamplerYcbcrRangeKHR = SamplerYcbcrRange

type ChromaLocation int32

type ChromaLocationKHR = ChromaLocation

type SubmitFlagBits int32

type SubmitFlagBitsKHR = SubmitFlagBits

type PFN_vkInternalAllocationNotification uintptr

type PFN_vkInternalFreeNotification uintptr

type PFN_vkReallocationFunction uintptr

type PFN_vkAllocationFunction uintptr

type PFN_vkFreeFunction uintptr

type PFN_vkVoidFunction uintptr

type Extent3D struct {
	Width  uint32
	Height uint32
	Depth  uint32
}

type ComponentMapping struct {
	R ComponentSwizzle
	G ComponentSwizzle
	B ComponentSwizzle
	A ComponentSwizzle
}

type PhysicalDeviceProperties struct {
	ApiVersion        uint32
	DriverVersion     uint32
	VendorID          uint32
	DeviceID          uint32
	DeviceType        PhysicalDeviceType
	DeviceName        [MaxPhysicalDeviceNameSize]byte
	PipelineCacheUUID [UUIDSize]uint8
	Limits            PhysicalDeviceLimits
	SparseProperties  PhysicalDeviceSparseProperties
}

type ExtensionProperties struct {
	ExtensionName [MaxExtensionNameSize]byte
	SpecVersion   uint32
}

type LayerProperties struct {
	LayerName             [MaxExtensionNameSize]byte
	SpecVersion           uint32
	ImplementationVersion uint32
	Description           [MaxDescriptionSize]byte
}

type ApplicationInfo struct {
	SType              StructureType
	Next               unsafe.Pointer
	ApplicationName    *byte
	ApplicationVersion uint32
	EngineName         *byte
	EngineVersion      uint32
	ApiVersion         uint32
}

type AllocationCallbacks struct {
	UserData              unsafe.Pointer
	PfnAllocation         PFN_vkAllocationFunction
	PfnReallocation       PFN_vkReallocationFunction
	PfnFree               PFN_vkFreeFunction
	PfnInternalAllocation PFN_vkInternalAllocationNotification
	PfnInternalFree       PFN_vkInternalFreeNotification
}

type DeviceQueueCreateInfo struct {
	SType            StructureType
	Next             unsafe.Pointer
	Flags            DeviceQueueCreateFlags
	QueueFamilyIndex uint32
	QueueCount       uint32
	QueuePriorities  *float32
}

type DeviceCreateInfo struct {
	SType                   StructureType
	Next                    unsafe.Pointer
	Flags                   DeviceCreateFlags
	QueueCreateInfoCount    uint32
	QueueCreateInfos        *DeviceQueueCreateInfo
	EnabledLayerCount       uint32
	PpEnabledLayerNames     **byte
	EnabledExtensionCount   uint32
	PpEnabledExtensionNames **byte
	EnabledFeatures         *PhysicalDeviceFeatures
}

type InstanceCreateInfo struct {
	SType                   StructureType
	Next                    unsafe.Pointer
	Flags                   InstanceCreateFlags
	ApplicationInfo         *ApplicationInfo
	EnabledLayerCount       uint32
	PpEnabledLayerNames     **byte
	EnabledExtensionCount   uint32
	PpEnabledExtensionNames **byte
}

type QueueFamilyProperties struct {
	QueueFlags                  QueueFlags
	QueueCount                  uint32
	TimestampValidBits          uint32
	MinImageTransferGranularity Extent3D
}

type PhysicalDeviceMemoryProperties struct {
	MemoryTypeCount uint32
	MemoryTypes     [MaxMemoryTypes]MemoryType
	MemoryHeapCount uint32
	MemoryHeaps     [MaxMemoryHeaps]MemoryHeap
}

type MemoryAllocateInfo struct {
	SType           StructureType
	Next            unsafe.Pointer
	AllocationSize  DeviceSize
	MemoryTypeIndex uint32
}

type MemoryRequirements struct {
	Size           DeviceSize
	Alignment      DeviceSize
	MemoryTypeBits uint32
}

type SparseImageFormatProperties struct {
	AspectMask       ImageAspectFlags
	ImageGranularity Extent3D
	Flags            SparseImageFormatFlags
}

type SparseImageMemoryRequirements struct {
	FormatProperties     SparseImageFormatProperties
	ImageMipTailFirstLod uint32
	ImageMipTailSize     DeviceSize
	ImageMipTailOffset   DeviceSize
	ImageMipTailStride   DeviceSize
}

type MemoryType struct {
	PropertyFlags MemoryPropertyFlags
	HeapIndex     uint32
}

type MemoryHeap struct {
	Size  DeviceSize
	Flags MemoryHeapFlags
}

type FormatProperties struct {
	LinearTilingFeatures  FormatFeatureFlags
	OptimalTilingFeatures FormatFeatureFlags
	BufferFeatures        FormatFeatureFlags
}

type ImageFormatProperties struct {
	MaxExtent       Extent3D
	MaxMipLevels    uint32
	MaxArrayLayers  uint32
	SampleCounts    SampleCountFlags
	MaxResourceSize DeviceSize
}

type DescriptorBufferInfo struct {
	Buffer Buffer
	Offset DeviceSize
	Range  DeviceSize
}

type DescriptorImageInfo struct {
	Sampler     Sampler
	ImageView   ImageView
	ImageLayout ImageLayout
}

type WriteDescriptorSet struct {
	SType           StructureType
	Next            unsafe.Pointer
	DstSet          DescriptorSet
	DstBinding      uint32
	DstArrayElement uint32
	DescriptorCount uint32
	DescriptorType  DescriptorType
	ImageInfo       *DescriptorImageInfo
	BufferInfo      *DescriptorBufferInfo
	TexelBufferView *BufferView
}

type CopyDescriptorSet struct {
	SType           StructureType
	Next            unsafe.Pointer
	SrcSet          DescriptorSet
	SrcBinding      uint32
	SrcArrayElement uint32
	DstSet          DescriptorSet
	DstBinding      uint32
	DstArrayElement uint32
	DescriptorCount uint32
}

type ImageSubresourceRange struct {
	AspectMask     ImageAspectFlags
	BaseMipLevel   uint32
	LevelCount     uint32
	BaseArrayLayer uint32
	LayerCount     uint32
}

type ImageCreateInfo struct {
	SType                 StructureType
	Next                  unsafe.Pointer
	Flags                 ImageCreateFlags
	ImageType             ImageType
	Format                Format
	Extent                Extent3D
	MipLevels             uint32
	ArrayLayers           uint32
	Samples               SampleCountFlagBits
	Tiling                ImageTiling
	Usage                 ImageUsageFlags
	SharingMode           SharingMode
	QueueFamilyIndexCount uint32
	QueueFamilyIndices    *uint32
	InitialLayout         ImageLayout
}

type SubresourceLayout struct {
	Offset     DeviceSize
	Size       DeviceSize
	RowPitch   DeviceSize
	ArrayPitch DeviceSize
	DepthPitch DeviceSize
}

type ImageViewCreateInfo struct {
	SType            StructureType
	Next             unsafe.Pointer
	Flags            ImageViewCreateFlags
	Image            Image
	ViewType         ImageViewType
	Format           Format
	Components       ComponentMapping
	SubresourceRange ImageSubresourceRange
}

type ShaderModuleCreateInfo struct {
	SType    StructureType
	Next     unsafe.Pointer
	Flags    ShaderModuleCreateFlags
	CodeSize uintptr
	Code     *uint32
}

type DescriptorSetLayoutBinding struct {
	Binding           uint32
	DescriptorType    DescriptorType
	DescriptorCount   uint32
	StageFlags        ShaderStageFlags
	ImmutableSamplers *Sampler
}

type DescriptorSetLayoutCreateInfo struct {
	SType        StructureType
	Next         unsafe.Pointer
	Flags        DescriptorSetLayoutCreateFlags
	BindingCount uint32
	Bindings     *DescriptorSetLayoutBinding
}

type DescriptorPoolSize struct {
	Type            DescriptorType
	DescriptorCount uint32
}

type DescriptorPoolCreateInfo struct {
	SType         StructureType
	Next          unsafe.Pointer
	Flags         DescriptorPoolCreateFlags
	MaxSets       uint32
	PoolSizeCount uint32
	PoolSizes     *DescriptorPoolSize
}

type DescriptorSetAllocateInfo struct {
	SType              StructureType
	Next               unsafe.Pointer
	DescriptorPool     DescriptorPool
	DescriptorSetCount uint32
	SetLayouts         *DescriptorSetLayout
}

type PushConstantRange struct {
	StageFlags ShaderStageFlags
	Offset     uint32
	Size       uint32
}

type PipelineLayoutCreateInfo struct {
	SType                  StructureType
	Next                   unsafe.Pointer
	Flags                  PipelineLayoutCreateFlags
	SetLayoutCount         uint32
	SetLayouts             *DescriptorSetLayout
	PushConstantRangeCount uint32
	PushConstantRanges     *PushConstantRange
}

type SamplerCreateInfo struct {
	SType                   StructureType
	Next                    unsafe.Pointer
	Flags                   SamplerCreateFlags
	MagFilter               Filter
	MinFilter               Filter
	MipmapMode              SamplerMipmapMode
	AddressModeU            SamplerAddressMode
	AddressModeV            SamplerAddressMode
	AddressModeW            SamplerAddressMode
	MipLodBias              float32
	AnisotropyEnable        Bool32
	MaxAnisotropy           float32
	CompareEnable           Bool32
	CompareOp               CompareOp
	MinLod                  float32
	MaxLod                  float32
	BorderColor             BorderColor
	UnnormalizedCoordinates Bool32
}

type CommandPoolCreateInfo struct {
	SType            StructureType
	Next             unsafe.Pointer
	Flags            CommandPoolCreateFlags
	QueueFamilyIndex uint32
}

type CommandBufferAllocateInfo struct {
	SType              StructureType
	Next               unsafe.Pointer
	CommandPool        CommandPool
	Level              CommandBufferLevel
	CommandBufferCount uint32
}

type CommandBufferInheritanceInfo struct {
	SType                StructureType
	Next                 unsafe.Pointer
	RenderPass           RenderPass
	Subpass              uint32
	Framebuffer          Framebuffer
	OcclusionQueryEnable Bool32
	QueryFlags           QueryControlFlags
	PipelineStatistics   QueryPipelineStatisticFlags
}

type CommandBufferBeginInfo struct {
	SType           StructureType
	Next            unsafe.Pointer
	Flags           CommandBufferUsageFlags
	InheritanceInfo *CommandBufferInheritanceInfo
}

type FenceCreateInfo struct {
	SType StructureType
	Next  unsafe.Pointer
	Flags FenceCreateFlags
}

type PhysicalDeviceFeatures struct {
	RobustBufferAccess                      Bool32
	FullDrawIndexUint32                     Bool32
	ImageCubeArray                          Bool32
	IndependentBlend                        Bool32
	GeometryShader                          Bool32
	TessellationShader                      Bool32
	SampleRateShading                       Bool32
	DualSrcBlend                            Bool32
	LogicOp                                 Bool32
	MultiDrawIndirect                       Bool32
	DrawIndirectFirstInstance               Bool32
	DepthClamp                              Bool32
	DepthBiasClamp                          Bool32
	FillModeNonSolid                        Bool32
	DepthBounds                             Bool32
	WideLines                               Bool32
	LargePoints                             Bool32
	AlphaToOne                              Bool32
	MultiViewport                           Bool32
	SamplerAnisotropy                       Bool32
	TextureCompressionETC2                  Bool32
	TextureCompressionASTC_LDR              Bool32
	TextureCompressionBC                    Bool32
	OcclusionQueryPrecise                   Bool32
	PipelineStatisticsQuery                 Bool32
	VertexPipelineStoresAndAtomics          Bool32
	FragmentStoresAndAtomics                Bool32
	ShaderTessellationAndGeometryPointSize  Bool32
	ShaderImageGatherExtended               Bool32
	ShaderStorageImageExtendedFormats       Bool32
	ShaderStorageImageMultisample           Bool32
	ShaderStorageImageReadWithoutFormat     Bool32
	ShaderStorageImageWriteWithoutFormat    Bool32
	ShaderUniformBufferArrayDynamicIndexing Bool32
	ShaderSampledImageArrayDynamicIndexing  Bool32
	ShaderStorageBufferArrayDynamicIndexing Bool32
	ShaderStorageImageArrayDynamicIndexing  Bool32
	ShaderClipDistance                      Bool32
	ShaderCullDistance                      Bool32
	ShaderFloat64                           Bool32
	ShaderInt64                             Bool32
	ShaderInt16                             Bool32
	ShaderResourceResidency                 Bool32
	ShaderResourceMinLod                    Bool32
	SparseBinding                           Bool32
	SparseResidencyBuffer                   Bool32
	SparseResidencyImage2D                  Bool32
	SparseResidencyImage3D                  Bool32
	SparseResidency2Samples                 Bool32
	SparseResidency4Samples                 Bool32
	SparseResidency8Samples                 Bool32
	SparseResidency16Samples                Bool32
	SparseResidencyAliased                  Bool32
	VariableMultisampleRate                 Bool32
	InheritedQueries                        Bool32
}

type PhysicalDeviceSparseProperties struct {
	ResidencyStandard2DBlockShape            Bool32
	ResidencyStandard2DMultisampleBlockShape Bool32
	ResidencyStandard3DBlockShape            Bool32
	ResidencyAlignedMipSize                  Bool32
	ResidencyNonResidentStrict               Bool32
}

type PhysicalDeviceLimits struct {
	MaxImageDimension1D                             uint32
	MaxImageDimension2D                             uint32
	MaxImageDimension3D                             uint32
	MaxImageDimensionCube                           uint32
	MaxImageArrayLayers                             uint32
	MaxTexelBufferElements                          uint32
	MaxUniformBufferRange                           uint32
	MaxStorageBufferRange                           uint32
	MaxPushConstantsSize                            uint32
	MaxMemoryAllocationCount                        uint32
	MaxSamplerAllocationCount                       uint32
	BufferImageGranularity                          DeviceSize
	SparseAddressSpaceSize                          DeviceSize
	MaxBoundDescriptorSets                          uint32
	MaxPerStageDescriptorSamplers                   uint32
	MaxPerStageDescriptorUniformBuffers             uint32
	MaxPerStageDescriptorStorageBuffers             uint32
	MaxPerStageDescriptorSampledImages              uint32
	MaxPerStageDescriptorStorageImages              uint32
	MaxPerStageDescriptorInputAttachments           uint32
	MaxPerStageResources                            uint32
	MaxDescriptorSetSamplers                        uint32
	MaxDescriptorSetUniformBuffers                  uint32
	MaxDescriptorSetUniformBuffersDynamic           uint32
	MaxDescriptorSetStorageBuffers                  uint32
	MaxDescriptorSetStorageBuffersDynamic           uint32
	MaxDescriptorSetSampledImages                   uint32
	MaxDescriptorSetStorageImages                   uint32
	MaxDescriptorSetInputAttachments                uint32
	MaxVertexInputAttributes                        uint32
	MaxVertexInputBindings                          uint32
	MaxVertexInputAttributeOffset                   uint32
	MaxVertexInputBindingStride                     uint32
	MaxVertexOutputComponents                       uint32
	MaxTessellationGenerationLevel                  uint32
	MaxTessellationPatchSize                        uint32
	MaxTessellationControlPerVertexInputComponents  uint32
	MaxTessellationControlPerVertexOutputComponents uint32
	MaxTessellationControlPerPatchOutputComponents  uint32
	MaxTessellationControlTotalOutputComponents     uint32
	MaxTessellationEvaluationInputComponents        uint32
	MaxTessellationEvaluationOutputComponents       uint32
	MaxGeometryShaderInvocations                    uint32
	MaxGeometryInputComponents                      uint32
	MaxGeometryOutputComponents                     uint32
	MaxGeometryOutputVertices                       uint32
	MaxGeometryTotalOutputComponents                uint32
	MaxFragmentInputComponents                      uint32
	MaxFragmentOutputAttachments                    uint32
	MaxFragmentDualSrcAttachments                   uint32
	MaxFragmentCombinedOutputResources              uint32
	MaxComputeSharedMemorySize                      uint32
	MaxComputeWorkGroupCount                        [3]uint32
	MaxComputeWorkGroupInvocations                  uint32
	MaxComputeWorkGroupSize                         [3]uint32
	SubPixelPrecisionBits                           uint32
	SubTexelPrecisionBits                           uint32
	MipmapPrecisionBits                             uint32
	MaxDrawIndexedIndexValue                        uint32
	MaxDrawIndirectCount                            uint32
	MaxSamplerLodBias                               float32
	MaxSamplerAnisotropy                            float32
	MaxViewports                                    uint32
	MaxViewportDimensions                           [2]uint32
	ViewportBoundsRange                             [2]float32
	ViewportSubPixelBits                            uint32
	MinMemoryMapAlignment                           uintptr
	MinTexelBufferOffsetAlignment                   DeviceSize
	MinUniformBufferOffsetAlignment                 DeviceSize
	MinStorageBufferOffsetAlignment                 DeviceSize
	MinTexelOffset                                  int32
	MaxTexelOffset                                  uint32
	MinTexelGatherOffset                            int32
	MaxTexelGatherOffset                            uint32
	MinInterpolationOffset                          float32
	MaxInterpolationOffset                          float32
	SubPixelInterpolationOffsetBits                 uint32
	MaxFramebufferWidth                             uint32
	MaxFramebufferHeight                            uint32
	MaxFramebufferLayers                            uint32
	FramebufferColorSampleCounts                    SampleCountFlags
	FramebufferDepthSampleCounts                    SampleCountFlags
	FramebufferStencilSampleCounts                  SampleCountFlags
	FramebufferNoAttachmentsSampleCounts            SampleCountFlags
	MaxColorAttachments                             uint32
	SampledImageColorSampleCounts                   SampleCountFlags
	SampledImageIntegerSampleCounts                 SampleCountFlags
	SampledImageDepthSampleCounts                   SampleCountFlags
	SampledImageStencilSampleCounts                 SampleCountFlags
	StorageImageSampleCounts                        SampleCountFlags
	MaxSampleMaskWords                              uint32
	TimestampComputeAndGraphics                     Bool32
	TimestampPeriod                                 float32
	MaxClipDistances                                uint32
	MaxCullDistances                                uint32
	MaxCombinedClipAndCullDistances                 uint32
	DiscreteQueuePriorities                         uint32
	PointSizeRange                                  [2]float32
	LineWidthRange                                  [2]float32
	PointSizeGranularity                            float32
	LineWidthGranularity                            float32
	StrictLines                                     Bool32
	StandardSampleLocations                         Bool32
	OptimalBufferCopyOffsetAlignment                DeviceSize
	OptimalBufferCopyRowPitchAlignment              DeviceSize
	NonCoherentAtomSize                             DeviceSize
}

type SemaphoreCreateInfo struct {
	SType StructureType
	Next  unsafe.Pointer
	Flags SemaphoreCreateFlags
}

type SubmitInfo struct {
	SType                StructureType
	Next                 unsafe.Pointer
	WaitSemaphoreCount   uint32
	WaitSemaphores       *Semaphore
	WaitDstStageMask     *PipelineStageFlags
	CommandBufferCount   uint32
	CommandBuffers       *CommandBuffer
	SignalSemaphoreCount uint32
	SignalSemaphores     *Semaphore
}

type PhysicalDeviceFeatures2 struct {
	SType    StructureType
	Next     unsafe.Pointer
	Features PhysicalDeviceFeatures
}

type PhysicalDeviceFeatures2KHR = PhysicalDeviceFeatures2

type PhysicalDeviceProperties2 struct {
	SType      StructureType
	Next       unsafe.Pointer
	Properties PhysicalDeviceProperties
}

type PhysicalDeviceProperties2KHR = PhysicalDeviceProperties2

type FormatProperties2 struct {
	SType            StructureType
	Next             unsafe.Pointer
	FormatProperties FormatProperties
}

type FormatProperties2KHR = FormatProperties2

type ImageFormatProperties2 struct {
	SType                 StructureType
	Next                  unsafe.Pointer
	ImageFormatProperties ImageFormatProperties
}

type ImageFormatProperties2KHR = ImageFormatProperties2

type PhysicalDeviceImageFormatInfo2 struct {
	SType  StructureType
	Next   unsafe.Pointer
	Format Format
	Type   ImageType
	Tiling ImageTiling
	Usage  ImageUsageFlags
	Flags  ImageCreateFlags
}

type PhysicalDeviceImageFormatInfo2KHR = PhysicalDeviceImageFormatInfo2

type QueueFamilyProperties2 struct {
	SType                 StructureType
	Next                  unsafe.Pointer
	QueueFamilyProperties QueueFamilyProperties
}

type QueueFamilyProperties2KHR = QueueFamilyProperties2

type PhysicalDeviceMemoryProperties2 struct {
	SType            StructureType
	Next             unsafe.Pointer
	MemoryProperties PhysicalDeviceMemoryProperties
}

type PhysicalDeviceMemoryProperties2KHR = PhysicalDeviceMemoryProperties2

type SparseImageFormatProperties2 struct {
	SType      StructureType
	Next       unsafe.Pointer
	Properties SparseImageFormatProperties
}

type SparseImageFormatProperties2KHR = SparseImageFormatProperties2

type PhysicalDeviceSparseImageFormatInfo2 struct {
	SType   StructureType
	Next    unsafe.Pointer
	Format  Format
	Type    ImageType
	Samples SampleCountFlagBits
	Usage   ImageUsageFlags
	Tiling  ImageTiling
}

type PhysicalDeviceSparseImageFormatInfo2KHR = PhysicalDeviceSparseImageFormatInfo2

type ExternalMemoryProperties struct {
	ExternalMemoryFeatures        ExternalMemoryFeatureFlags
	ExportFromImportedHandleTypes ExternalMemoryHandleTypeFlags
	CompatibleHandleTypes         ExternalMemoryHandleTypeFlags
}

type ExternalMemoryPropertiesKHR = ExternalMemoryProperties

type PhysicalDeviceExternalImageFormatInfo struct {
	SType      StructureType
	Next       unsafe.Pointer
	HandleType ExternalMemoryHandleTypeFlagBits
}

type PhysicalDeviceExternalImageFormatInfoKHR = PhysicalDeviceExternalImageFormatInfo

type ExternalImageFormatProperties struct {
	SType                    StructureType
	Next                     unsafe.Pointer
	ExternalMemoryProperties ExternalMemoryProperties
}

type ExternalImageFormatPropertiesKHR = ExternalImageFormatProperties

type PhysicalDeviceExternalBufferInfo struct {
	SType      StructureType
	Next       unsafe.Pointer
	Flags      BufferCreateFlags
	Usage      BufferUsageFlags
	HandleType ExternalMemoryHandleTypeFlagBits
}

type PhysicalDeviceExternalBufferInfoKHR = PhysicalDeviceExternalBufferInfo

type ExternalBufferProperties struct {
	SType                    StructureType
	Next                     unsafe.Pointer
	ExternalMemoryProperties ExternalMemoryProperties
}

type ExternalBufferPropertiesKHR = ExternalBufferProperties

type PhysicalDeviceIDProperties struct {
	SType           StructureType
	Next            unsafe.Pointer
	DeviceUUID      [UUIDSize]uint8
	DriverUUID      [UUIDSize]uint8
	DeviceLUID      [LUIDSize]uint8
	DeviceNodeMask  uint32
	DeviceLUIDValid Bool32
}

type PhysicalDeviceIDPropertiesKHR = PhysicalDeviceIDProperties

type ExternalMemoryImageCreateInfo struct {
	SType       StructureType
	Next        unsafe.Pointer
	HandleTypes ExternalMemoryHandleTypeFlags
}

type ExternalMemoryImageCreateInfoKHR = ExternalMemoryImageCreateInfo

type ExternalMemoryBufferCreateInfo struct {
	SType       StructureType
	Next        unsafe.Pointer
	HandleTypes ExternalMemoryHandleTypeFlags
}

type ExternalMemoryBufferCreateInfoKHR = ExternalMemoryBufferCreateInfo

type ExportMemoryAllocateInfo struct {
	SType       StructureType
	Next        unsafe.Pointer
	HandleTypes ExternalMemoryHandleTypeFlags
}

type ExportMemoryAllocateInfoKHR = ExportMemoryAllocateInfo

type ImportMemoryFdInfoKHR struct {
	SType      StructureType
	Next       unsafe.Pointer
	HandleType ExternalMemoryHandleTypeFlagBits
	Fd         int32
}

type MemoryFdPropertiesKHR struct {
	SType          StructureType
	Next           unsafe.Pointer
	MemoryTypeBits uint32
}

type MemoryGetFdInfoKHR struct {
	SType      StructureType
	Next       unsafe.Pointer
	Memory     DeviceMemory
	HandleType ExternalMemoryHandleTypeFlagBits
}

type PhysicalDeviceExternalSemaphoreInfo struct {
	SType      StructureType
	Next       unsafe.Pointer
	HandleType ExternalSemaphoreHandleTypeFlagBits
}

type PhysicalDeviceExternalSemaphoreInfoKHR = PhysicalDeviceExternalSemaphoreInfo

type ExternalSemaphoreProperties struct {
	SType                         StructureType
	Next                          unsafe.Pointer
	ExportFromImportedHandleTypes ExternalSemaphoreHandleTypeFlags
	CompatibleHandleTypes         ExternalSemaphoreHandleTypeFlags
	ExternalSemaphoreFeatures     ExternalSemaphoreFeatureFlags
}

type ExternalSemaphorePropertiesKHR = ExternalSemaphoreProperties

type ExportSemaphoreCreateInfo struct {
	SType       StructureType
	Next        unsafe.Pointer
	HandleTypes ExternalSemaphoreHandleTypeFlags
}

type ExportSemaphoreCreateInfoKHR = ExportSemaphoreCreateInfo

type ImportSemaphoreFdInfoKHR struct {
	SType      StructureType
	Next       unsafe.Pointer
	Semaphore  Semaphore
	Flags      SemaphoreImportFlags
	HandleType ExternalSemaphoreHandleTypeFlagBits
	Fd         int32
}

type SemaphoreGetFdInfoKHR struct {
	SType      StructureType
	Next       unsafe.Pointer
	Semaphore  Semaphore
	HandleType ExternalSemaphoreHandleTypeFlagBits
}

type BindBufferMemoryInfo struct {
	SType        StructureType
	Next         unsafe.Pointer
	Buffer       Buffer
	Memory       DeviceMemory
	MemoryOffset DeviceSize
}

type BindBufferMemoryInfoKHR = BindBufferMemoryInfo

type BindImageMemoryInfo struct {
	SType        StructureType
	Next         unsafe.Pointer
	Image        Image
	Memory       DeviceMemory
	MemoryOffset DeviceSize
}

type BindImageMemoryInfoKHR = BindImageMemoryInfo

type BufferMemoryRequirementsInfo2 struct {
	SType  StructureType
	Next   unsafe.Pointer
	Buffer Buffer
}

type BufferMemoryRequirementsInfo2KHR = BufferMemoryRequirementsInfo2

type ImageMemoryRequirementsInfo2 struct {
	SType StructureType
	Next  unsafe.Pointer
	Image Image
}

type ImageMemoryRequirementsInfo2KHR = ImageMemoryRequirementsInfo2

type ImageSparseMemoryRequirementsInfo2 struct {
	SType StructureType
	Next  unsafe.Pointer
	Image Image
}

type ImageSparseMemoryRequirementsInfo2KHR = ImageSparseMemoryRequirementsInfo2

type MemoryRequirements2 struct {
	SType              StructureType
	Next               unsafe.Pointer
	MemoryRequirements MemoryRequirements
}

type MemoryRequirements2KHR = MemoryRequirements2

type SparseImageMemoryRequirements2 struct {
	SType              StructureType
	Next               unsafe.Pointer
	MemoryRequirements SparseImageMemoryRequirements
}

type SparseImageMemoryRequirements2KHR = SparseImageMemoryRequirements2

type SamplerYcbcrConversionInfo struct {
	SType      StructureType
	Next       unsafe.Pointer
	Conversion SamplerYcbcrConversion
}

type SamplerYcbcrConversionInfoKHR = SamplerYcbcrConversionInfo

type SamplerYcbcrConversionCreateInfo struct {
	SType                       StructureType
	Next                        unsafe.Pointer
	Format                      Format
	YcbcrModel                  SamplerYcbcrModelConversion
	YcbcrRange                  SamplerYcbcrRange
	Components                  ComponentMapping
	XChromaOffset               ChromaLocation
	YChromaOffset               ChromaLocation
	ChromaFilter                Filter
	ForceExplicitReconstruction Bool32
}

type SamplerYcbcrConversionCreateInfoKHR = SamplerYcbcrConversionCreateInfo

type BindImagePlaneMemoryInfo struct {
	SType       StructureType
	Next        unsafe.Pointer
	PlaneAspect ImageAspectFlagBits
}

type BindImagePlaneMemoryInfoKHR = BindImagePlaneMemoryInfo

type ImagePlaneMemoryRequirementsInfo struct {
	SType       StructureType
	Next        unsafe.Pointer
	PlaneAspect ImageAspectFlagBits
}

type ImagePlaneMemoryRequirementsInfoKHR = ImagePlaneMemoryRequirementsInfo

type PhysicalDeviceSamplerYcbcrConversionFeatures struct {
	SType                  StructureType
	Next                   unsafe.Pointer
	SamplerYcbcrConversion Bool32
}

type PhysicalDeviceSamplerYcbcrConversionFeaturesKHR = PhysicalDeviceSamplerYcbcrConversionFeatures

type SamplerYcbcrConversionImageFormatProperties struct {
	SType                               StructureType
	Next                                unsafe.Pointer
	CombinedImageSamplerDescriptorCount uint32
}

type SamplerYcbcrConversionImageFormatPropertiesKHR = SamplerYcbcrConversionImageFormatProperties

type ImageFormatListCreateInfo struct {
	SType           StructureType
	Next            unsafe.Pointer
	ViewFormatCount uint32
	ViewFormats     *Format
}

type ImageFormatListCreateInfoKHR = ImageFormatListCreateInfo

type DrmFormatModifierPropertiesListEXT struct {
	SType                       StructureType
	Next                        unsafe.Pointer
	DrmFormatModifierCount      uint32
	DrmFormatModifierProperties *DrmFormatModifierPropertiesEXT
}

type DrmFormatModifierPropertiesEXT struct {
	DrmFormatModifier               uint64
	DrmFormatModifierPlaneCount     uint32
	DrmFormatModifierTilingFeatures FormatFeatureFlags
}

type PhysicalDeviceImageDrmFormatModifierInfoEXT struct {
	SType                 StructureType
	Next                  unsafe.Pointer
	DrmFormatModifier     uint64
	SharingMode           SharingMode
	QueueFamilyIndexCount uint32
	QueueFamilyIndices    *uint32
}

type ImageDrmFormatModifierListCreateInfoEXT struct {
	SType                  StructureType
	Next                   unsafe.Pointer
	DrmFormatModifierCount uint32
	DrmFormatModifiers     *uint64
}

type ImageDrmFormatModifierExplicitCreateInfoEXT struct {
	SType                       StructureType
	Next                        unsafe.Pointer
	DrmFormatModifier           uint64
	DrmFormatModifierPlaneCount uint32
	PlaneLayouts                *SubresourceLayout
}

type ImageDrmFormatModifierPropertiesEXT struct {
	SType             StructureType
	Next              unsafe.Pointer
	DrmFormatModifier uint64
}

type MemoryBarrier2 struct {
	SType         StructureType
	Next          unsafe.Pointer
	SrcStageMask  PipelineStageFlags2
	SrcAccessMask AccessFlags2
	DstStageMask  PipelineStageFlags2
	DstAccessMask AccessFlags2
}

type MemoryBarrier2KHR = MemoryBarrier2

type ImageMemoryBarrier2 struct {
	SType               StructureType
	Next                unsafe.Pointer
	SrcStageMask        PipelineStageFlags2
	SrcAccessMask       AccessFlags2
	DstStageMask        PipelineStageFlags2
	DstAccessMask       AccessFlags2
	OldLayout           ImageLayout
	NewLayout           ImageLayout
	SrcQueueFamilyIndex uint32
	DstQueueFamilyIndex uint32
	Image               Image
	SubresourceRange    ImageSubresourceRange
}

type ImageMemoryBarrier2KHR = ImageMemoryBarrier2

type BufferMemoryBarrier2 struct {
	SType               StructureType
	Next                unsafe.Pointer
	SrcStageMask        PipelineStageFlags2
	SrcAccessMask       AccessFlags2
	DstStageMask        PipelineStageFlags2
	DstAccessMask       AccessFlags2
	SrcQueueFamilyIndex uint32
	DstQueueFamilyIndex uint32
	Buffer              Buffer
	Offset              DeviceSize
	Size                DeviceSize
}

type BufferMemoryBarrier2KHR = BufferMemoryBarrier2

type DependencyInfo struct {
	SType                    StructureType
	Next                     unsafe.Pointer
	DependencyFlags          DependencyFlags
	MemoryBarrierCount       uint32
	MemoryBarriers           *MemoryBarrier2
	BufferMemoryBarrierCount uint32
	BufferMemoryBarriers     *BufferMemoryBarrier2
	ImageMemoryBarrierCount  uint32
	ImageMemoryBarriers      *ImageMemoryBarrier2
}

type DependencyInfoKHR = DependencyInfo

type SemaphoreSubmitInfo struct {
	SType       StructureType
	Next        unsafe.Pointer
	Semaphore   Semaphore
	Value       uint64
	StageMask   PipelineStageFlags2
	DeviceIndex uint32
}

type SemaphoreSubmitInfoKHR = SemaphoreSubmitInfo

type CommandBufferSubmitInfo struct {
	SType         StructureType
	Next          unsafe.Pointer
	CommandBuffer CommandBuffer
	DeviceMask    uint32
}

type CommandBufferSubmitInfoKHR = CommandBufferSubmitInfo

type SubmitInfo2 struct {
	SType                    StructureType
	Next                     unsafe.Pointer
	Flags                    SubmitFlags
	WaitSemaphoreInfoCount   uint32
	WaitSemaphoreInfos       *SemaphoreSubmitInfo
	CommandBufferInfoCount   uint32
	CommandBufferInfos       *CommandBufferSubmitInfo
	SignalSemaphoreInfoCount uint32
	SignalSemaphoreInfos     *SemaphoreSubmitInfo
}

type SubmitInfo2KHR = SubmitInfo2

type PhysicalDeviceSynchronization2Features struct {
	SType            StructureType
	Next             unsafe.Pointer
	Synchronization2 Bool32
}

type PhysicalDeviceSynchronization2FeaturesKHR = PhysicalDeviceSynchronization2Features

type PhysicalDeviceDrmPropertiesEXT struct {
	SType        StructureType
	Next         unsafe.Pointer
	HasPrimary   Bool32
	HasRender    Bool32
	PrimaryMajor int64
	PrimaryMinor int64
	RenderMajor  int64
	RenderMinor  int64
}
