// Code generated by vulkangen. DO NOT EDIT.

package capi

import (
	"fmt"
	"strings"
)

type LookupFunc func(handle uintptr, name string) (uintptr, error)

func RegisterGlobal(handle uintptr, lookup LookupFunc, fptrs map[string]any) error {
	if err := registerRequired([]string{"vkCreateInstance"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkGetInstanceProcAddr"}, handle, lookup, fptrs); err != nil {
		return err
	}
	registerOptional([]string{"vkEnumerateInstanceVersion"}, handle, lookup, fptrs)
	if err := registerRequired([]string{"vkEnumerateInstanceLayerProperties"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkEnumerateInstanceExtensionProperties"}, handle, lookup, fptrs); err != nil {
		return err
	}
	return nil
}

func RegisterInstance(handle uintptr, lookup LookupFunc, fptrs map[string]any) error {
	if err := registerRequired([]string{"vkDestroyInstance"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkEnumeratePhysicalDevices"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkGetDeviceProcAddr"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkGetPhysicalDeviceProperties"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkGetPhysicalDeviceQueueFamilyProperties"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkCreateDevice"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkEnumerateDeviceExtensionProperties"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkGetPhysicalDeviceFeatures2", "vkGetPhysicalDeviceFeatures2KHR"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkGetPhysicalDeviceProperties2", "vkGetPhysicalDeviceProperties2KHR"}, handle, lookup, fptrs); err != nil {
		return err
	}
	registerOptional([]string{"vkGetPhysicalDeviceFormatProperties2KHR"}, handle, lookup, fptrs)
	registerOptional([]string{"vkGetPhysicalDeviceImageFormatProperties2KHR"}, handle, lookup, fptrs)
	if err := registerRequired([]string{"vkGetPhysicalDeviceQueueFamilyProperties2", "vkGetPhysicalDeviceQueueFamilyProperties2KHR"}, handle, lookup, fptrs); err != nil {
		return err
	}
	registerOptional([]string{"vkGetPhysicalDeviceMemoryProperties2KHR"}, handle, lookup, fptrs)
	registerOptional([]string{"vkGetPhysicalDeviceSparseImageFormatProperties2KHR"}, handle, lookup, fptrs)
	registerOptional([]string{"vkGetPhysicalDeviceExternalBufferPropertiesKHR"}, handle, lookup, fptrs)
	registerOptional([]string{"vkGetPhysicalDeviceExternalSemaphorePropertiesKHR"}, handle, lookup, fptrs)
	return nil
}

func RegisterDevice(handle uintptr, lookup LookupFunc, fptrs map[string]any) error {
	if err := registerRequired([]string{"vkDestroyDevice"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkGetDeviceQueue"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkQueueSubmit"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkQueueWaitIdle"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkDeviceWaitIdle"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkAllocateMemory"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkFreeMemory"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkGetImageMemoryRequirements"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkBindImageMemory"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkCreateFence"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkDestroyFence"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkResetFences"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkWaitForFences"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkCreateSemaphore"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkDestroySemaphore"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkCreateImage"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkDestroyImage"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkCreateImageView"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkDestroyImageView"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkCreateShaderModule"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkDestroyShaderModule"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkCreatePipelineLayout"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkDestroyPipelineLayout"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkCreateSampler"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkDestroySampler"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkCreateDescriptorSetLayout"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkDestroyDescriptorSetLayout"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkCreateDescriptorPool"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkDestroyDescriptorPool"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkAllocateDescriptorSets"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkUpdateDescriptorSets"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkCreateCommandPool"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkDestroyCommandPool"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkAllocateCommandBuffers"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkFreeCommandBuffers"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkBeginCommandBuffer"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkEndCommandBuffer"}, handle, lookup, fptrs); err != nil {
		return err
	}
	if err := registerRequired([]string{"vkResetCommandBuffer"}, handle, lookup, fptrs); err != nil {
		return err
	}
	registerOptional([]string{"vkTrimCommandPoolKHR"}, handle, lookup, fptrs)
	registerOptional([]string{"vkGetMemoryFdKHR"}, handle, lookup, fptrs)
	registerOptional([]string{"vkGetMemoryFdPropertiesKHR"}, handle, lookup, fptrs)
	registerOptional([]string{"vkGetSemaphoreFdKHR"}, handle, lookup, fptrs)
	registerOptional([]string{"vkImportSemaphoreFdKHR"}, handle, lookup, fptrs)
	registerOptional([]string{"vkBindBufferMemory2KHR"}, handle, lookup, fptrs)
	if err := registerRequired([]string{"vkBindImageMemory2", "vkBindImageMemory2KHR"}, handle, lookup, fptrs); err != nil {
		return err
	}
	registerOptional([]string{"vkGetBufferMemoryRequirements2KHR"}, handle, lookup, fptrs)
	if err := registerRequired([]string{"vkGetImageMemoryRequirements2", "vkGetImageMemoryRequirements2KHR"}, handle, lookup, fptrs); err != nil {
		return err
	}
	registerOptional([]string{"vkGetImageSparseMemoryRequirements2KHR"}, handle, lookup, fptrs)
	registerOptional([]string{"vkCreateSamplerYcbcrConversionKHR"}, handle, lookup, fptrs)
	registerOptional([]string{"vkDestroySamplerYcbcrConversionKHR"}, handle, lookup, fptrs)
	registerOptional([]string{"vkGetImageDrmFormatModifierPropertiesEXT"}, handle, lookup, fptrs)
	registerOptional([]string{"vkCmdSetEvent2KHR"}, handle, lookup, fptrs)
	registerOptional([]string{"vkCmdResetEvent2KHR"}, handle, lookup, fptrs)
	registerOptional([]string{"vkCmdWaitEvents2KHR"}, handle, lookup, fptrs)
	registerOptional([]string{"vkCmdPipelineBarrier2KHR"}, handle, lookup, fptrs)
	registerOptional([]string{"vkQueueSubmit2KHR"}, handle, lookup, fptrs)
	registerOptional([]string{"vkCmdWriteTimestamp2KHR"}, handle, lookup, fptrs)
	return nil
}

func registerRequired(names []string, handle uintptr, lookup LookupFunc, fptrs map[string]any) error {
	if err := requireFunctionPointers(names, fptrs); err != nil {
		return err
	}
	if registerFirstAvailable(names, handle, lookup, fptrs) {
		return nil
	}
	return fmt.Errorf("resolve %s: no symbol found", strings.Join(names, " or "))
}

func registerOptional(names []string, handle uintptr, lookup LookupFunc, fptrs map[string]any) {
	registerFirstAvailable(names, handle, lookup, fptrs)
}

func requireFunctionPointers(names []string, fptrs map[string]any) error {
	for _, name := range names {
		fptr, ok := fptrs[name]
		if !ok || fptr == nil {
			return fmt.Errorf("missing function pointer for %s", name)
		}
	}
	return nil
}

func registerFirstAvailable(names []string, handle uintptr, lookup LookupFunc, fptrs map[string]any) bool {
	for _, name := range names {
		addr, err := lookup(handle, name)
		if err != nil || addr == 0 {
			continue
		}
		registerAddress(names, addr, fptrs)
		return true
	}
	return false
}

func registerAddress(names []string, addr uintptr, fptrs map[string]any) {
	for _, name := range names {
		fptr, ok := fptrs[name]
		if !ok || fptr == nil {
			continue
		}
		RegisterFunc(fptr, addr)
	}
}
